#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Teacher
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ERP_Teacher")]
	public partial class loginteachDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertclasse(classe instance);
    partial void Updateclasse(classe instance);
    partial void Deleteclasse(classe instance);
    partial void InsertAdministrator(Administrator instance);
    partial void UpdateAdministrator(Administrator instance);
    partial void DeleteAdministrator(Administrator instance);
    partial void Insertenseignant(enseignant instance);
    partial void Updateenseignant(enseignant instance);
    partial void Deleteenseignant(enseignant instance);
    partial void Insertenseignant_mod(enseignant_mod instance);
    partial void Updateenseignant_mod(enseignant_mod instance);
    partial void Deleteenseignant_mod(enseignant_mod instance);
    partial void Insertenseigner(enseigner instance);
    partial void Updateenseigner(enseigner instance);
    partial void Deleteenseigner(enseigner instance);
    partial void Insertmec(mec instance);
    partial void Updatemec(mec instance);
    partial void Deletemec(mec instance);
    partial void Insertmodule(module instance);
    partial void Updatemodule(module instance);
    partial void Deletemodule(module instance);
    partial void InsertNotification(Notification instance);
    partial void UpdateNotification(Notification instance);
    partial void DeleteNotification(Notification instance);
    partial void Insertemploi_enseignant(emploi_enseignant instance);
    partial void Updateemploi_enseignant(emploi_enseignant instance);
    partial void Deleteemploi_enseignant(emploi_enseignant instance);
    #endregion
		
		public loginteachDataContext() : 
				base(global::ERP_Teacher.Properties.Settings.Default.ERP_TeacherConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public loginteachDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public loginteachDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public loginteachDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public loginteachDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<classe> classes
		{
			get
			{
				return this.GetTable<classe>();
			}
		}
		
		public System.Data.Linq.Table<Administrator> Administrators
		{
			get
			{
				return this.GetTable<Administrator>();
			}
		}
		
		public System.Data.Linq.Table<enseignant> enseignants
		{
			get
			{
				return this.GetTable<enseignant>();
			}
		}
		
		public System.Data.Linq.Table<enseignant_mod> enseignant_mods
		{
			get
			{
				return this.GetTable<enseignant_mod>();
			}
		}
		
		public System.Data.Linq.Table<enseigner> enseigners
		{
			get
			{
				return this.GetTable<enseigner>();
			}
		}
		
		public System.Data.Linq.Table<mec> mecs
		{
			get
			{
				return this.GetTable<mec>();
			}
		}
		
		public System.Data.Linq.Table<module> modules
		{
			get
			{
				return this.GetTable<module>();
			}
		}
		
		public System.Data.Linq.Table<Notification> Notifications
		{
			get
			{
				return this.GetTable<Notification>();
			}
		}
		
		public System.Data.Linq.Table<emploi_enseignant> emploi_enseignants
		{
			get
			{
				return this.GetTable<emploi_enseignant>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.classe")]
	public partial class classe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_classe;
		
		private string _section;
		
		private System.Nullable<int> _niveau;
		
		private string _annee_etude;
		
		private System.Nullable<int> _groupe;
		
		private EntitySet<enseigner> _enseigners;
		
		private EntitySet<mec> _mecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_classeChanging(int value);
    partial void Onid_classeChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    partial void OnniveauChanging(System.Nullable<int> value);
    partial void OnniveauChanged();
    partial void Onannee_etudeChanging(string value);
    partial void Onannee_etudeChanged();
    partial void OngroupeChanging(System.Nullable<int> value);
    partial void OngroupeChanged();
    #endregion
		
		public classe()
		{
			this._enseigners = new EntitySet<enseigner>(new Action<enseigner>(this.attach_enseigners), new Action<enseigner>(this.detach_enseigners));
			this._mecs = new EntitySet<mec>(new Action<mec>(this.attach_mecs), new Action<mec>(this.detach_mecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_classe", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_classe
		{
			get
			{
				return this._id_classe;
			}
			set
			{
				if ((this._id_classe != value))
				{
					this.Onid_classeChanging(value);
					this.SendPropertyChanging();
					this._id_classe = value;
					this.SendPropertyChanged("id_classe");
					this.Onid_classeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="VarChar(50)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this.OnsectionChanging(value);
					this.SendPropertyChanging();
					this._section = value;
					this.SendPropertyChanged("section");
					this.OnsectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int")]
		public System.Nullable<int> niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this.OnniveauChanging(value);
					this.SendPropertyChanging();
					this._niveau = value;
					this.SendPropertyChanged("niveau");
					this.OnniveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annee_etude", DbType="VarChar(50)")]
		public string annee_etude
		{
			get
			{
				return this._annee_etude;
			}
			set
			{
				if ((this._annee_etude != value))
				{
					this.Onannee_etudeChanging(value);
					this.SendPropertyChanging();
					this._annee_etude = value;
					this.SendPropertyChanged("annee_etude");
					this.Onannee_etudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupe", DbType="Int")]
		public System.Nullable<int> groupe
		{
			get
			{
				return this._groupe;
			}
			set
			{
				if ((this._groupe != value))
				{
					this.OngroupeChanging(value);
					this.SendPropertyChanging();
					this._groupe = value;
					this.SendPropertyChanged("groupe");
					this.OngroupeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classe_enseigner", Storage="_enseigners", ThisKey="id_classe", OtherKey="id_classe")]
		public EntitySet<enseigner> enseigners
		{
			get
			{
				return this._enseigners;
			}
			set
			{
				this._enseigners.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classe_mec", Storage="_mecs", ThisKey="id_classe", OtherKey="classe")]
		public EntitySet<mec> mecs
		{
			get
			{
				return this._mecs;
			}
			set
			{
				this._mecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.classe = this;
		}
		
		private void detach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.classe = null;
		}
		
		private void attach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.classe1 = this;
		}
		
		private void detach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.classe1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Administrator")]
	public partial class Administrator : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cin;
		
		private string _mot_de_passe;
		
		private string _nom;
		
		private string _prenom;
		
		private string _mail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncinChanging(string value);
    partial void OncinChanged();
    partial void Onmot_de_passeChanging(string value);
    partial void Onmot_de_passeChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    #endregion
		
		public Administrator()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cin
		{
			get
			{
				return this._cin;
			}
			set
			{
				if ((this._cin != value))
				{
					this.OncinChanging(value);
					this.SendPropertyChanging();
					this._cin = value;
					this.SendPropertyChanged("cin");
					this.OncinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mot_de_passe", DbType="VarChar(50)")]
		public string mot_de_passe
		{
			get
			{
				return this._mot_de_passe;
			}
			set
			{
				if ((this._mot_de_passe != value))
				{
					this.Onmot_de_passeChanging(value);
					this.SendPropertyChanging();
					this._mot_de_passe = value;
					this.SendPropertyChanged("mot_de_passe");
					this.Onmot_de_passeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(50)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(50)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(50)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enseignant")]
	public partial class enseignant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cin;
		
		private string _nom;
		
		private string _prenom;
		
		private string _mots_de_passe;
		
		private System.Data.Linq.Binary _code_a_bar;
		
		private string _mail;
		
		private System.Data.Linq.Binary _photo;
		
		private string _fbid;
		
		private string _gmailid;
		
		private EntitySet<enseignant_mod> _enseignant_mods;
		
		private EntitySet<enseigner> _enseigners;
		
		private EntitySet<mec> _mecs;
		
		private EntitySet<Notification> _Notifications;
		
		private EntitySet<emploi_enseignant> _emploi_enseignants;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncinChanging(string value);
    partial void OncinChanged();
    partial void OnnomChanging(string value);
    partial void OnnomChanged();
    partial void OnprenomChanging(string value);
    partial void OnprenomChanged();
    partial void Onmots_de_passeChanging(string value);
    partial void Onmots_de_passeChanged();
    partial void Oncode_a_barChanging(System.Data.Linq.Binary value);
    partial void Oncode_a_barChanged();
    partial void OnmailChanging(string value);
    partial void OnmailChanged();
    partial void OnphotoChanging(System.Data.Linq.Binary value);
    partial void OnphotoChanged();
    partial void OnfbidChanging(string value);
    partial void OnfbidChanged();
    partial void OngmailidChanging(string value);
    partial void OngmailidChanged();
    #endregion
		
		public enseignant()
		{
			this._enseignant_mods = new EntitySet<enseignant_mod>(new Action<enseignant_mod>(this.attach_enseignant_mods), new Action<enseignant_mod>(this.detach_enseignant_mods));
			this._enseigners = new EntitySet<enseigner>(new Action<enseigner>(this.attach_enseigners), new Action<enseigner>(this.detach_enseigners));
			this._mecs = new EntitySet<mec>(new Action<mec>(this.attach_mecs), new Action<mec>(this.detach_mecs));
			this._Notifications = new EntitySet<Notification>(new Action<Notification>(this.attach_Notifications), new Action<Notification>(this.detach_Notifications));
			this._emploi_enseignants = new EntitySet<emploi_enseignant>(new Action<emploi_enseignant>(this.attach_emploi_enseignants), new Action<emploi_enseignant>(this.detach_emploi_enseignants));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cin
		{
			get
			{
				return this._cin;
			}
			set
			{
				if ((this._cin != value))
				{
					this.OncinChanging(value);
					this.SendPropertyChanging();
					this._cin = value;
					this.SendPropertyChanged("cin");
					this.OncinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom", DbType="VarChar(25)")]
		public string nom
		{
			get
			{
				return this._nom;
			}
			set
			{
				if ((this._nom != value))
				{
					this.OnnomChanging(value);
					this.SendPropertyChanging();
					this._nom = value;
					this.SendPropertyChanged("nom");
					this.OnnomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prenom", DbType="VarChar(25)")]
		public string prenom
		{
			get
			{
				return this._prenom;
			}
			set
			{
				if ((this._prenom != value))
				{
					this.OnprenomChanging(value);
					this.SendPropertyChanging();
					this._prenom = value;
					this.SendPropertyChanged("prenom");
					this.OnprenomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mots_de_passe", DbType="VarChar(25)")]
		public string mots_de_passe
		{
			get
			{
				return this._mots_de_passe;
			}
			set
			{
				if ((this._mots_de_passe != value))
				{
					this.Onmots_de_passeChanging(value);
					this.SendPropertyChanging();
					this._mots_de_passe = value;
					this.SendPropertyChanged("mots_de_passe");
					this.Onmots_de_passeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code_a_bar", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary code_a_bar
		{
			get
			{
				return this._code_a_bar;
			}
			set
			{
				if ((this._code_a_bar != value))
				{
					this.Oncode_a_barChanging(value);
					this.SendPropertyChanging();
					this._code_a_bar = value;
					this.SendPropertyChanged("code_a_bar");
					this.Oncode_a_barChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail", DbType="VarChar(40)")]
		public string mail
		{
			get
			{
				return this._mail;
			}
			set
			{
				if ((this._mail != value))
				{
					this.OnmailChanging(value);
					this.SendPropertyChanging();
					this._mail = value;
					this.SendPropertyChanged("mail");
					this.OnmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_photo", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary photo
		{
			get
			{
				return this._photo;
			}
			set
			{
				if ((this._photo != value))
				{
					this.OnphotoChanging(value);
					this.SendPropertyChanging();
					this._photo = value;
					this.SendPropertyChanged("photo");
					this.OnphotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fbid", DbType="VarChar(50)")]
		public string fbid
		{
			get
			{
				return this._fbid;
			}
			set
			{
				if ((this._fbid != value))
				{
					this.OnfbidChanging(value);
					this.SendPropertyChanging();
					this._fbid = value;
					this.SendPropertyChanged("fbid");
					this.OnfbidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gmailid", DbType="VarChar(50)")]
		public string gmailid
		{
			get
			{
				return this._gmailid;
			}
			set
			{
				if ((this._gmailid != value))
				{
					this.OngmailidChanging(value);
					this.SendPropertyChanging();
					this._gmailid = value;
					this.SendPropertyChanged("gmailid");
					this.OngmailidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_enseignant_mod", Storage="_enseignant_mods", ThisKey="cin", OtherKey="cin_enseignant")]
		public EntitySet<enseignant_mod> enseignant_mods
		{
			get
			{
				return this._enseignant_mods;
			}
			set
			{
				this._enseignant_mods.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_enseigner", Storage="_enseigners", ThisKey="cin", OtherKey="cin_enseignant")]
		public EntitySet<enseigner> enseigners
		{
			get
			{
				return this._enseigners;
			}
			set
			{
				this._enseigners.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_mec", Storage="_mecs", ThisKey="cin", OtherKey="cin")]
		public EntitySet<mec> mecs
		{
			get
			{
				return this._mecs;
			}
			set
			{
				this._mecs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_Notification", Storage="_Notifications", ThisKey="cin", OtherKey="id_ens")]
		public EntitySet<Notification> Notifications
		{
			get
			{
				return this._Notifications;
			}
			set
			{
				this._Notifications.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_emploi_enseignant", Storage="_emploi_enseignants", ThisKey="cin", OtherKey="id_ens")]
		public EntitySet<emploi_enseignant> emploi_enseignants
		{
			get
			{
				return this._emploi_enseignants;
			}
			set
			{
				this._emploi_enseignants.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enseignant_mods(enseignant_mod entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = this;
		}
		
		private void detach_enseignant_mods(enseignant_mod entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = null;
		}
		
		private void attach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = this;
		}
		
		private void detach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = null;
		}
		
		private void attach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = this;
		}
		
		private void detach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = null;
		}
		
		private void attach_Notifications(Notification entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = this;
		}
		
		private void detach_Notifications(Notification entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = null;
		}
		
		private void attach_emploi_enseignants(emploi_enseignant entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = this;
		}
		
		private void detach_emploi_enseignants(emploi_enseignant entity)
		{
			this.SendPropertyChanging();
			entity.enseignant = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enseignant_mod")]
	public partial class enseignant_mod : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cin_enseignant;
		
		private string _id_module;
		
		private string _volume_h;
		
		private string _type_ens;
		
		private EntityRef<enseignant> _enseignant;
		
		private EntityRef<module> _module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncin_enseignantChanging(string value);
    partial void Oncin_enseignantChanged();
    partial void Onid_moduleChanging(string value);
    partial void Onid_moduleChanged();
    partial void Onvolume_hChanging(string value);
    partial void Onvolume_hChanged();
    partial void Ontype_ensChanging(string value);
    partial void Ontype_ensChanged();
    #endregion
		
		public enseignant_mod()
		{
			this._enseignant = default(EntityRef<enseignant>);
			this._module = default(EntityRef<module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin_enseignant", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cin_enseignant
		{
			get
			{
				return this._cin_enseignant;
			}
			set
			{
				if ((this._cin_enseignant != value))
				{
					if (this._enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncin_enseignantChanging(value);
					this.SendPropertyChanging();
					this._cin_enseignant = value;
					this.SendPropertyChanged("cin_enseignant");
					this.Oncin_enseignantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_module", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_module
		{
			get
			{
				return this._id_module;
			}
			set
			{
				if ((this._id_module != value))
				{
					if (this._module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_moduleChanging(value);
					this.SendPropertyChanging();
					this._id_module = value;
					this.SendPropertyChanged("id_module");
					this.Onid_moduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume_h", DbType="VarChar(50)")]
		public string volume_h
		{
			get
			{
				return this._volume_h;
			}
			set
			{
				if ((this._volume_h != value))
				{
					this.Onvolume_hChanging(value);
					this.SendPropertyChanging();
					this._volume_h = value;
					this.SendPropertyChanged("volume_h");
					this.Onvolume_hChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_ens", DbType="VarChar(50)")]
		public string type_ens
		{
			get
			{
				return this._type_ens;
			}
			set
			{
				if ((this._type_ens != value))
				{
					this.Ontype_ensChanging(value);
					this.SendPropertyChanging();
					this._type_ens = value;
					this.SendPropertyChanged("type_ens");
					this.Ontype_ensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_enseignant_mod", Storage="_enseignant", ThisKey="cin_enseignant", OtherKey="cin", IsForeignKey=true)]
		public enseignant enseignant
		{
			get
			{
				return this._enseignant.Entity;
			}
			set
			{
				enseignant previousValue = this._enseignant.Entity;
				if (((previousValue != value) 
							|| (this._enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enseignant.Entity = null;
						previousValue.enseignant_mods.Remove(this);
					}
					this._enseignant.Entity = value;
					if ((value != null))
					{
						value.enseignant_mods.Add(this);
						this._cin_enseignant = value.cin;
					}
					else
					{
						this._cin_enseignant = default(string);
					}
					this.SendPropertyChanged("enseignant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_enseignant_mod", Storage="_module", ThisKey="id_module", OtherKey="id_module", IsForeignKey=true)]
		public module module
		{
			get
			{
				return this._module.Entity;
			}
			set
			{
				module previousValue = this._module.Entity;
				if (((previousValue != value) 
							|| (this._module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._module.Entity = null;
						previousValue.enseignant_mods.Remove(this);
					}
					this._module.Entity = value;
					if ((value != null))
					{
						value.enseignant_mods.Add(this);
						this._id_module = value.id_module;
					}
					else
					{
						this._id_module = default(string);
					}
					this.SendPropertyChanged("module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.enseigner")]
	public partial class enseigner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _cin_enseignant;
		
		private int _id_classe;
		
		private string _id_module;
		
		private string _heure;
		
		private string _salle;
		
		private string _jour;
		
		private EntityRef<classe> _classe;
		
		private EntityRef<enseignant> _enseignant;
		
		private EntityRef<module> _module;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncin_enseignantChanging(string value);
    partial void Oncin_enseignantChanged();
    partial void Onid_classeChanging(int value);
    partial void Onid_classeChanged();
    partial void Onid_moduleChanging(string value);
    partial void Onid_moduleChanged();
    partial void OnheureChanging(string value);
    partial void OnheureChanged();
    partial void OnsalleChanging(string value);
    partial void OnsalleChanged();
    partial void OnjourChanging(string value);
    partial void OnjourChanged();
    #endregion
		
		public enseigner()
		{
			this._classe = default(EntityRef<classe>);
			this._enseignant = default(EntityRef<enseignant>);
			this._module = default(EntityRef<module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin_enseignant", DbType="VarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cin_enseignant
		{
			get
			{
				return this._cin_enseignant;
			}
			set
			{
				if ((this._cin_enseignant != value))
				{
					if (this._enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Oncin_enseignantChanging(value);
					this.SendPropertyChanging();
					this._cin_enseignant = value;
					this.SendPropertyChanged("cin_enseignant");
					this.Oncin_enseignantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_classe", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_classe
		{
			get
			{
				return this._id_classe;
			}
			set
			{
				if ((this._id_classe != value))
				{
					if (this._classe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_classeChanging(value);
					this.SendPropertyChanging();
					this._id_classe = value;
					this.SendPropertyChanged("id_classe");
					this.Onid_classeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_module", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_module
		{
			get
			{
				return this._id_module;
			}
			set
			{
				if ((this._id_module != value))
				{
					if (this._module.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_moduleChanging(value);
					this.SendPropertyChanging();
					this._id_module = value;
					this.SendPropertyChanged("id_module");
					this.Onid_moduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure", DbType="VarChar(50)")]
		public string heure
		{
			get
			{
				return this._heure;
			}
			set
			{
				if ((this._heure != value))
				{
					this.OnheureChanging(value);
					this.SendPropertyChanging();
					this._heure = value;
					this.SendPropertyChanged("heure");
					this.OnheureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salle", DbType="VarChar(50)")]
		public string salle
		{
			get
			{
				return this._salle;
			}
			set
			{
				if ((this._salle != value))
				{
					this.OnsalleChanging(value);
					this.SendPropertyChanging();
					this._salle = value;
					this.SendPropertyChanged("salle");
					this.OnsalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jour", DbType="VarChar(50)")]
		public string jour
		{
			get
			{
				return this._jour;
			}
			set
			{
				if ((this._jour != value))
				{
					this.OnjourChanging(value);
					this.SendPropertyChanging();
					this._jour = value;
					this.SendPropertyChanged("jour");
					this.OnjourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classe_enseigner", Storage="_classe", ThisKey="id_classe", OtherKey="id_classe", IsForeignKey=true)]
		public classe classe
		{
			get
			{
				return this._classe.Entity;
			}
			set
			{
				classe previousValue = this._classe.Entity;
				if (((previousValue != value) 
							|| (this._classe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._classe.Entity = null;
						previousValue.enseigners.Remove(this);
					}
					this._classe.Entity = value;
					if ((value != null))
					{
						value.enseigners.Add(this);
						this._id_classe = value.id_classe;
					}
					else
					{
						this._id_classe = default(int);
					}
					this.SendPropertyChanged("classe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_enseigner", Storage="_enseignant", ThisKey="cin_enseignant", OtherKey="cin", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public enseignant enseignant
		{
			get
			{
				return this._enseignant.Entity;
			}
			set
			{
				enseignant previousValue = this._enseignant.Entity;
				if (((previousValue != value) 
							|| (this._enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enseignant.Entity = null;
						previousValue.enseigners.Remove(this);
					}
					this._enseignant.Entity = value;
					if ((value != null))
					{
						value.enseigners.Add(this);
						this._cin_enseignant = value.cin;
					}
					else
					{
						this._cin_enseignant = default(string);
					}
					this.SendPropertyChanged("enseignant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_enseigner", Storage="_module", ThisKey="id_module", OtherKey="id_module", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public module module
		{
			get
			{
				return this._module.Entity;
			}
			set
			{
				module previousValue = this._module.Entity;
				if (((previousValue != value) 
							|| (this._module.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._module.Entity = null;
						previousValue.enseigners.Remove(this);
					}
					this._module.Entity = value;
					if ((value != null))
					{
						value.enseigners.Add(this);
						this._id_module = value.id_module;
					}
					else
					{
						this._id_module = default(string);
					}
					this.SendPropertyChanged("module");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.mec")]
	public partial class mec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cin;
		
		private string _module;
		
		private System.Nullable<int> _classe;
		
		private EntityRef<classe> _classe1;
		
		private EntityRef<enseignant> _enseignant;
		
		private EntityRef<module> _module1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncinChanging(string value);
    partial void OncinChanged();
    partial void OnmoduleChanging(string value);
    partial void OnmoduleChanged();
    partial void OnclasseChanging(System.Nullable<int> value);
    partial void OnclasseChanged();
    #endregion
		
		public mec()
		{
			this._classe1 = default(EntityRef<classe>);
			this._enseignant = default(EntityRef<enseignant>);
			this._module1 = default(EntityRef<module>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cin", DbType="VarChar(8)")]
		public string cin
		{
			get
			{
				return this._cin;
			}
			set
			{
				if ((this._cin != value))
				{
					if (this._enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncinChanging(value);
					this.SendPropertyChanging();
					this._cin = value;
					this.SendPropertyChanged("cin");
					this.OncinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module", DbType="VarChar(50)")]
		public string module
		{
			get
			{
				return this._module;
			}
			set
			{
				if ((this._module != value))
				{
					if (this._module1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmoduleChanging(value);
					this.SendPropertyChanging();
					this._module = value;
					this.SendPropertyChanged("module");
					this.OnmoduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classe", DbType="Int")]
		public System.Nullable<int> classe
		{
			get
			{
				return this._classe;
			}
			set
			{
				if ((this._classe != value))
				{
					if (this._classe1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnclasseChanging(value);
					this.SendPropertyChanging();
					this._classe = value;
					this.SendPropertyChanged("classe");
					this.OnclasseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="classe_mec", Storage="_classe1", ThisKey="classe", OtherKey="id_classe", IsForeignKey=true, DeleteRule="CASCADE")]
		public classe classe1
		{
			get
			{
				return this._classe1.Entity;
			}
			set
			{
				classe previousValue = this._classe1.Entity;
				if (((previousValue != value) 
							|| (this._classe1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._classe1.Entity = null;
						previousValue.mecs.Remove(this);
					}
					this._classe1.Entity = value;
					if ((value != null))
					{
						value.mecs.Add(this);
						this._classe = value.id_classe;
					}
					else
					{
						this._classe = default(Nullable<int>);
					}
					this.SendPropertyChanged("classe1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_mec", Storage="_enseignant", ThisKey="cin", OtherKey="cin", IsForeignKey=true, DeleteRule="CASCADE")]
		public enseignant enseignant
		{
			get
			{
				return this._enseignant.Entity;
			}
			set
			{
				enseignant previousValue = this._enseignant.Entity;
				if (((previousValue != value) 
							|| (this._enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enseignant.Entity = null;
						previousValue.mecs.Remove(this);
					}
					this._enseignant.Entity = value;
					if ((value != null))
					{
						value.mecs.Add(this);
						this._cin = value.cin;
					}
					else
					{
						this._cin = default(string);
					}
					this.SendPropertyChanged("enseignant");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_mec", Storage="_module1", ThisKey="module", OtherKey="id_module", IsForeignKey=true, DeleteRule="CASCADE")]
		public module module1
		{
			get
			{
				return this._module1.Entity;
			}
			set
			{
				module previousValue = this._module1.Entity;
				if (((previousValue != value) 
							|| (this._module1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._module1.Entity = null;
						previousValue.mecs.Remove(this);
					}
					this._module1.Entity = value;
					if ((value != null))
					{
						value.mecs.Add(this);
						this._module = value.id_module;
					}
					else
					{
						this._module = default(string);
					}
					this.SendPropertyChanged("module1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.module")]
	public partial class module : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_module;
		
		private string _nom_module;
		
		private System.Nullable<int> _volume_h;
		
		private string _regime;
		
		private System.Nullable<decimal> _coefficient;
		
		private string _url;
		
		private string _email;
		
		private string _annee_etude;
		
		private System.Nullable<int> _niveau;
		
		private EntitySet<enseignant_mod> _enseignant_mods;
		
		private EntitySet<enseigner> _enseigners;
		
		private EntitySet<mec> _mecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_moduleChanging(string value);
    partial void Onid_moduleChanged();
    partial void Onnom_moduleChanging(string value);
    partial void Onnom_moduleChanged();
    partial void Onvolume_hChanging(System.Nullable<int> value);
    partial void Onvolume_hChanged();
    partial void OnregimeChanging(string value);
    partial void OnregimeChanged();
    partial void OncoefficientChanging(System.Nullable<decimal> value);
    partial void OncoefficientChanged();
    partial void OnurlChanging(string value);
    partial void OnurlChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onannee_etudeChanging(string value);
    partial void Onannee_etudeChanged();
    partial void OnniveauChanging(System.Nullable<int> value);
    partial void OnniveauChanged();
    #endregion
		
		public module()
		{
			this._enseignant_mods = new EntitySet<enseignant_mod>(new Action<enseignant_mod>(this.attach_enseignant_mods), new Action<enseignant_mod>(this.detach_enseignant_mods));
			this._enseigners = new EntitySet<enseigner>(new Action<enseigner>(this.attach_enseigners), new Action<enseigner>(this.detach_enseigners));
			this._mecs = new EntitySet<mec>(new Action<mec>(this.attach_mecs), new Action<mec>(this.detach_mecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_module", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_module
		{
			get
			{
				return this._id_module;
			}
			set
			{
				if ((this._id_module != value))
				{
					this.Onid_moduleChanging(value);
					this.SendPropertyChanging();
					this._id_module = value;
					this.SendPropertyChanged("id_module");
					this.Onid_moduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nom_module", DbType="VarChar(50)")]
		public string nom_module
		{
			get
			{
				return this._nom_module;
			}
			set
			{
				if ((this._nom_module != value))
				{
					this.Onnom_moduleChanging(value);
					this.SendPropertyChanging();
					this._nom_module = value;
					this.SendPropertyChanged("nom_module");
					this.Onnom_moduleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_volume_h", DbType="Int")]
		public System.Nullable<int> volume_h
		{
			get
			{
				return this._volume_h;
			}
			set
			{
				if ((this._volume_h != value))
				{
					this.Onvolume_hChanging(value);
					this.SendPropertyChanging();
					this._volume_h = value;
					this.SendPropertyChanged("volume_h");
					this.Onvolume_hChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regime", DbType="VarChar(50)")]
		public string regime
		{
			get
			{
				return this._regime;
			}
			set
			{
				if ((this._regime != value))
				{
					this.OnregimeChanging(value);
					this.SendPropertyChanging();
					this._regime = value;
					this.SendPropertyChanged("regime");
					this.OnregimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coefficient", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> coefficient
		{
			get
			{
				return this._coefficient;
			}
			set
			{
				if ((this._coefficient != value))
				{
					this.OncoefficientChanging(value);
					this.SendPropertyChanging();
					this._coefficient = value;
					this.SendPropertyChanged("coefficient");
					this.OncoefficientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_url", DbType="VarChar(50)")]
		public string url
		{
			get
			{
				return this._url;
			}
			set
			{
				if ((this._url != value))
				{
					this.OnurlChanging(value);
					this.SendPropertyChanging();
					this._url = value;
					this.SendPropertyChanged("url");
					this.OnurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_annee_etude", DbType="VarChar(50)")]
		public string annee_etude
		{
			get
			{
				return this._annee_etude;
			}
			set
			{
				if ((this._annee_etude != value))
				{
					this.Onannee_etudeChanging(value);
					this.SendPropertyChanging();
					this._annee_etude = value;
					this.SendPropertyChanged("annee_etude");
					this.Onannee_etudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_niveau", DbType="Int")]
		public System.Nullable<int> niveau
		{
			get
			{
				return this._niveau;
			}
			set
			{
				if ((this._niveau != value))
				{
					this.OnniveauChanging(value);
					this.SendPropertyChanging();
					this._niveau = value;
					this.SendPropertyChanged("niveau");
					this.OnniveauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_enseignant_mod", Storage="_enseignant_mods", ThisKey="id_module", OtherKey="id_module")]
		public EntitySet<enseignant_mod> enseignant_mods
		{
			get
			{
				return this._enseignant_mods;
			}
			set
			{
				this._enseignant_mods.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_enseigner", Storage="_enseigners", ThisKey="id_module", OtherKey="id_module")]
		public EntitySet<enseigner> enseigners
		{
			get
			{
				return this._enseigners;
			}
			set
			{
				this._enseigners.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="module_mec", Storage="_mecs", ThisKey="id_module", OtherKey="module")]
		public EntitySet<mec> mecs
		{
			get
			{
				return this._mecs;
			}
			set
			{
				this._mecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_enseignant_mods(enseignant_mod entity)
		{
			this.SendPropertyChanging();
			entity.module = this;
		}
		
		private void detach_enseignant_mods(enseignant_mod entity)
		{
			this.SendPropertyChanging();
			entity.module = null;
		}
		
		private void attach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.module = this;
		}
		
		private void detach_enseigners(enseigner entity)
		{
			this.SendPropertyChanging();
			entity.module = null;
		}
		
		private void attach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.module1 = this;
		}
		
		private void detach_mecs(mec entity)
		{
			this.SendPropertyChanging();
			entity.module1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Notification")]
	public partial class Notification : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_notif;
		
		private string _description;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _id_ens;
		
		private EntityRef<enseignant> _enseignant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_notifChanging(int value);
    partial void Onid_notifChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void Onid_ensChanging(string value);
    partial void Onid_ensChanged();
    #endregion
		
		public Notification()
		{
			this._enseignant = default(EntityRef<enseignant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_notif", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_notif
		{
			get
			{
				return this._id_notif;
			}
			set
			{
				if ((this._id_notif != value))
				{
					this.Onid_notifChanging(value);
					this.SendPropertyChanging();
					this._id_notif = value;
					this.SendPropertyChanged("id_notif");
					this.Onid_notifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(50)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ens", DbType="VarChar(8)")]
		public string id_ens
		{
			get
			{
				return this._id_ens;
			}
			set
			{
				if ((this._id_ens != value))
				{
					if (this._enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ensChanging(value);
					this.SendPropertyChanging();
					this._id_ens = value;
					this.SendPropertyChanged("id_ens");
					this.Onid_ensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_Notification", Storage="_enseignant", ThisKey="id_ens", OtherKey="cin", IsForeignKey=true)]
		public enseignant enseignant
		{
			get
			{
				return this._enseignant.Entity;
			}
			set
			{
				enseignant previousValue = this._enseignant.Entity;
				if (((previousValue != value) 
							|| (this._enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enseignant.Entity = null;
						previousValue.Notifications.Remove(this);
					}
					this._enseignant.Entity = value;
					if ((value != null))
					{
						value.Notifications.Add(this);
						this._id_ens = value.cin;
					}
					else
					{
						this._id_ens = default(string);
					}
					this.SendPropertyChanged("enseignant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.emploi_enseignant")]
	public partial class emploi_enseignant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tache;
		
		private string _type;
		
		private System.Nullable<System.DateTime> _date;
		
		private string _heure_deb;
		
		private string _heure_fin;
		
		private string _salle;
		
		private string _id_ens;
		
		private EntityRef<enseignant> _enseignant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tacheChanging(int value);
    partial void Onid_tacheChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    partial void Onheure_debChanging(string value);
    partial void Onheure_debChanged();
    partial void Onheure_finChanging(string value);
    partial void Onheure_finChanged();
    partial void OnsalleChanging(string value);
    partial void OnsalleChanged();
    partial void Onid_ensChanging(string value);
    partial void Onid_ensChanged();
    #endregion
		
		public emploi_enseignant()
		{
			this._enseignant = default(EntityRef<enseignant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tache", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_tache
		{
			get
			{
				return this._id_tache;
			}
			set
			{
				if ((this._id_tache != value))
				{
					this.Onid_tacheChanging(value);
					this.SendPropertyChanging();
					this._id_tache = value;
					this.SendPropertyChanged("id_tache");
					this.Onid_tacheChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="VarChar(50)")]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this.OntypeChanging(value);
					this.SendPropertyChanging();
					this._type = value;
					this.SendPropertyChanged("type");
					this.OntypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="Date")]
		public System.Nullable<System.DateTime> date
		{
			get
			{
				return this._date;
			}
			set
			{
				if ((this._date != value))
				{
					this.OndateChanging(value);
					this.SendPropertyChanging();
					this._date = value;
					this.SendPropertyChanged("date");
					this.OndateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_deb", DbType="VarChar(50)")]
		public string heure_deb
		{
			get
			{
				return this._heure_deb;
			}
			set
			{
				if ((this._heure_deb != value))
				{
					this.Onheure_debChanging(value);
					this.SendPropertyChanging();
					this._heure_deb = value;
					this.SendPropertyChanged("heure_deb");
					this.Onheure_debChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_heure_fin", DbType="VarChar(50)")]
		public string heure_fin
		{
			get
			{
				return this._heure_fin;
			}
			set
			{
				if ((this._heure_fin != value))
				{
					this.Onheure_finChanging(value);
					this.SendPropertyChanging();
					this._heure_fin = value;
					this.SendPropertyChanged("heure_fin");
					this.Onheure_finChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salle", DbType="VarChar(50)")]
		public string salle
		{
			get
			{
				return this._salle;
			}
			set
			{
				if ((this._salle != value))
				{
					this.OnsalleChanging(value);
					this.SendPropertyChanging();
					this._salle = value;
					this.SendPropertyChanged("salle");
					this.OnsalleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ens", DbType="VarChar(8)")]
		public string id_ens
		{
			get
			{
				return this._id_ens;
			}
			set
			{
				if ((this._id_ens != value))
				{
					if (this._enseignant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_ensChanging(value);
					this.SendPropertyChanging();
					this._id_ens = value;
					this.SendPropertyChanged("id_ens");
					this.Onid_ensChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="enseignant_emploi_enseignant", Storage="_enseignant", ThisKey="id_ens", OtherKey="cin", IsForeignKey=true, DeleteRule="CASCADE")]
		public enseignant enseignant
		{
			get
			{
				return this._enseignant.Entity;
			}
			set
			{
				enseignant previousValue = this._enseignant.Entity;
				if (((previousValue != value) 
							|| (this._enseignant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._enseignant.Entity = null;
						previousValue.emploi_enseignants.Remove(this);
					}
					this._enseignant.Entity = value;
					if ((value != null))
					{
						value.emploi_enseignants.Add(this);
						this._id_ens = value.cin;
					}
					else
					{
						this._id_ens = default(string);
					}
					this.SendPropertyChanged("enseignant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
